// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: event/EventService.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
	EventDuration    int64                  `protobuf:"varint,4,opt,name=eventDuration,proto3" json:"eventDuration,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	UserId           string                 `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	NotificationTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=notificationTime,proto3,oneof" json:"notificationTime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Event) GetEventDuration() int64 {
	if x != nil {
		return x.EventDuration
	}
	return 0
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetNotificationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationTime
	}
	return nil
}

type UpdateEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dateTime,proto3,oneof" json:"dateTime,omitempty"`
	EventDuration    *int64                 `protobuf:"varint,4,opt,name=eventDuration,proto3,oneof" json:"eventDuration,omitempty"`
	Description      *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	NotificationTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=notificationTime,proto3,oneof" json:"notificationTime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateEventRequest) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *UpdateEventRequest) GetEventDuration() int64 {
	if x != nil && x.EventDuration != nil {
		return *x.EventDuration
	}
	return 0
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetNotificationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotificationTime
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{3}
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{4}
}

type GetByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByUserIdRequest) Reset() {
	*x = GetByUserIdRequest{}
	mi := &file_event_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByUserIdRequest) ProtoMessage() {}

func (x *GetByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *GetByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByIdRequest) Reset() {
	*x = ByIdRequest{}
	mi := &file_event_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByIdRequest) ProtoMessage() {}

func (x *ByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByIdRequest.ProtoReflect.Descriptor instead.
func (*ByIdRequest) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *ByIdRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_event_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *EventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_event_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_event_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *EventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_event_EventService_proto protoreflect.FileDescriptor

const file_event_EventService_proto_rawDesc = "" +
	"\n" +
	"\x18event/EventService.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xa7\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\bdateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12$\n" +
	"\reventDuration\x18\x04 \x01(\x03R\reventDuration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06userId\x18\x06 \x01(\tR\x06userId\x12K\n" +
	"\x10notificationTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x10notificationTime\x88\x01\x01B\x13\n" +
	"\x11_notificationTime\"\xe9\x02\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12;\n" +
	"\bdateTime\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdateTime\x88\x01\x01\x12)\n" +
	"\reventDuration\x18\x04 \x01(\x03H\x02R\reventDuration\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12K\n" +
	"\x10notificationTime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x10notificationTime\x88\x01\x01B\b\n" +
	"\x06_titleB\v\n" +
	"\t_dateTimeB\x10\n" +
	"\x0e_eventDurationB\x0e\n" +
	"\f_descriptionB\x13\n" +
	"\x11_notificationTime\"8\n" +
	"\x12CreateEventRequest\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\x15\n" +
	"\x13CreateEventResponse\"\x15\n" +
	"\x13DeleteEventResponse\",\n" +
	"\x12GetByUserIdRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"'\n" +
	"\vByIdRequest\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\"6\n" +
	"\x0eEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\"3\n" +
	"\rEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event2\xf0\x03\n" +
	"\fEventService\x12_\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/events\x12l\n" +
	"\x11GetEventsByUserID\x12\x19.event.GetByUserIdRequest\x1a\x15.event.EventsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/events/users/{userId}\x12U\n" +
	"\aGetById\x12\x12.event.ByIdRequest\x1a\x14.event.EventResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/events/{eventId}\x12Y\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x14.event.EventResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/api/v1/events\x12_\n" +
	"\vDeleteEvent\x12\x12.event.ByIdRequest\x1a\x1a.event.DeleteEventResponse\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/events/{eventId}B\x06Z\x04/;pbb\x06proto3"

var (
	file_event_EventService_proto_rawDescOnce sync.Once
	file_event_EventService_proto_rawDescData []byte
)

func file_event_EventService_proto_rawDescGZIP() []byte {
	file_event_EventService_proto_rawDescOnce.Do(func() {
		file_event_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_EventService_proto_rawDesc), len(file_event_EventService_proto_rawDesc)))
	})
	return file_event_EventService_proto_rawDescData
}

var file_event_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_event_EventService_proto_goTypes = []any{
	(*Event)(nil),                 // 0: event.Event
	(*UpdateEventRequest)(nil),    // 1: event.UpdateEventRequest
	(*CreateEventRequest)(nil),    // 2: event.CreateEventRequest
	(*CreateEventResponse)(nil),   // 3: event.CreateEventResponse
	(*DeleteEventResponse)(nil),   // 4: event.DeleteEventResponse
	(*GetByUserIdRequest)(nil),    // 5: event.GetByUserIdRequest
	(*ByIdRequest)(nil),           // 6: event.ByIdRequest
	(*EventsResponse)(nil),        // 7: event.EventsResponse
	(*EventResponse)(nil),         // 8: event.EventResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_event_EventService_proto_depIdxs = []int32{
	9,  // 0: event.Event.dateTime:type_name -> google.protobuf.Timestamp
	9,  // 1: event.Event.notificationTime:type_name -> google.protobuf.Timestamp
	9,  // 2: event.UpdateEventRequest.dateTime:type_name -> google.protobuf.Timestamp
	9,  // 3: event.UpdateEventRequest.notificationTime:type_name -> google.protobuf.Timestamp
	0,  // 4: event.CreateEventRequest.event:type_name -> event.Event
	0,  // 5: event.EventsResponse.events:type_name -> event.Event
	0,  // 6: event.EventResponse.event:type_name -> event.Event
	2,  // 7: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	5,  // 8: event.EventService.GetEventsByUserID:input_type -> event.GetByUserIdRequest
	6,  // 9: event.EventService.GetById:input_type -> event.ByIdRequest
	1,  // 10: event.EventService.UpdateEvent:input_type -> event.UpdateEventRequest
	6,  // 11: event.EventService.DeleteEvent:input_type -> event.ByIdRequest
	3,  // 12: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	7,  // 13: event.EventService.GetEventsByUserID:output_type -> event.EventsResponse
	8,  // 14: event.EventService.GetById:output_type -> event.EventResponse
	8,  // 15: event.EventService.UpdateEvent:output_type -> event.EventResponse
	4,  // 16: event.EventService.DeleteEvent:output_type -> event.DeleteEventResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_event_EventService_proto_init() }
func file_event_EventService_proto_init() {
	if File_event_EventService_proto != nil {
		return
	}
	file_event_EventService_proto_msgTypes[0].OneofWrappers = []any{}
	file_event_EventService_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_EventService_proto_rawDesc), len(file_event_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_EventService_proto_goTypes,
		DependencyIndexes: file_event_EventService_proto_depIdxs,
		MessageInfos:      file_event_EventService_proto_msgTypes,
	}.Build()
	File_event_EventService_proto = out.File
	file_event_EventService_proto_goTypes = nil
	file_event_EventService_proto_depIdxs = nil
}
